### ISSUE TITLE
Add to FreeCAD-addons Repo

### ISSUE THREAD

**Issue by luzpaz** [gbroques/ose-3d-printer-workbench#9]
https://github.com/FreeCAD/FreeCAD-addons

**Comment by gbroques** [comment]
Hi @luzpaz, thanks for suggesting this idea!

I'd like to add the workbench to the FreeCAD-addons repo once the workbench is further developed and polished--likely in a couple more months once summer starts.

This currently is not a high-priority item for me as FreeCAD 16 is my main targeted user-base in which the Addon Manager is unavailable.

**Comment by luzpaz** [comment]
I see. Ok. good luck then.

**Comment by gbroques** [comment]
We're working towards an initial `v0.1.0` release.

See [the v0.1.0 milestone](https://github.com/gbroques/ose-3d-printer-workbench/milestone/1) for progress.

I'm planning on addressing this after that milestone is achieved.

**Comment by gbroques** [comment]
@luzpaz See related PRs to add this workbench to the FreeCAD-addons repo:
* https://github.com/FreeCAD/FreeCAD-addons/pull/167
* https://github.com/FreeCAD/FreeCAD/pull/3379

**Comment by gbroques** [comment]
**TODO:** We should add a status badge to the README once this is complete like the following:

[![FreeCAD Addon Manager Status](https://img.shields.io/badge/FreeCAD%20Addon%20manager-available-brightgreen)](https://github.com/FreeCAD/FreeCAD-addons)

**Comment by gbroques** [comment]
https://github.com/FreeCAD/FreeCAD-addons/pull/167
